# Common configurations
server:
  servlet:
    context-path: /dove
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

spring:
  application:
    name: dove-common
  
  # Internationalization
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: false
  
  # Database common configurations
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  
  # JPA common configurations
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Logging common configurations
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.doveaccelerator: DEBUG

# Prompt engine configurations
prompt:
  engine:
    models:
      gpt4:
        apiEndpoint: ${GPT4_API_ENDPOINT:https://api.openai.com/v1}
        defaultTemperature: 0.7
        defaultMaxTokens: 2000
      claude:
        apiEndpoint: ${CLAUDE_API_ENDPOINT:https://api.anthropic.com/v1}
        defaultTemperature: 0.7
        defaultMaxTokens: 2000
    template:
      enableCache: true
      cacheSize: 1000
      defaultLanguage: en
    evaluation:
      enabled: true
      sampleSize: 100
      accuracyThreshold: 0.8
      latencyThreshold: 2000