# Application common configurations
server:
  port: 8081
  servlet:
    context-path: /dove-auth

spring:
  application:
    name: dove-auth

  # Database configuration
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dove_auth}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      pool-name: AuthHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

  # Redis configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

  # i18n configuration
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:dovesecretkeymustbelongerthanthirtytwobytes}
  expiration: ${JWT_EXPIRATION:3600000}  # 1 hour
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.doveaccelerator: INFO
    org.springframework: WARN
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Jackson Configuration
jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: UTC